package com.myspace.employee_rostering;

import java.time.LocalDateTime;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DayOffRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private LocalDateTime date;
	private com.myspace.employee_rostering.Employee employee;

	public DayOffRequest() {
	}

	public com.myspace.employee_rostering.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(com.myspace.employee_rostering.Employee employee) {
		this.employee = employee;
	}

	public java.time.LocalDateTime getDate() {
		return this.date;
	}

	public void setDate(java.time.LocalDateTime date) {
		this.date = date;
	}

	public DayOffRequest(java.time.LocalDateTime date,
			com.myspace.employee_rostering.Employee employee) {
		this.date = date;
		this.employee = employee;
	}

}