package com.myspace.employee_rostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution(autoDiscoverMemberType = org.optaplanner.core.api.domain.autodiscover.AutoDiscoverMemberType.FIELD)
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class EmployeeRoster implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.employee_rostering.DayOffRequest> dayOffRequestList;
	private java.util.List<com.myspace.employee_rostering.ShiftAssignment> shiftAssignmentList;
	private java.util.List<com.myspace.employee_rostering.Shift> shiftList;
	private java.util.List<com.myspace.employee_rostering.Skill> skillList;
	private java.util.List<com.myspace.employee_rostering.Timeslot> timeslotList;

	@javax.annotation.Generated(value = {"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(value = org.optaplanner.persistence.jaxb.api.score.buildin.hardsoft.HardSoftScoreJaxbXmlAdapter.class)
	@org.kie.api.definition.type.Label(value = "Generated Planner score field")
	@org.optaplanner.core.api.domain.solution.PlanningScore
	private org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score;

	@org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "employeeRange")
	private java.util.List<com.myspace.employee_rostering.Employee> employeeList;

	public EmployeeRoster() {
	}

	public java.util.List<com.myspace.employee_rostering.DayOffRequest> getDayOffRequestList() {
		return this.dayOffRequestList;
	}

	public void setDayOffRequestList(
			java.util.List<com.myspace.employee_rostering.DayOffRequest> dayOffRequestList) {
		this.dayOffRequestList = dayOffRequestList;
	}

	public java.util.List<com.myspace.employee_rostering.ShiftAssignment> getShiftAssignmentList() {
		return this.shiftAssignmentList;
	}

	public void setShiftAssignmentList(
			java.util.List<com.myspace.employee_rostering.ShiftAssignment> shiftAssignmentList) {
		this.shiftAssignmentList = shiftAssignmentList;
	}

	public java.util.List<com.myspace.employee_rostering.Shift> getShiftList() {
		return this.shiftList;
	}

	public void setShiftList(
			java.util.List<com.myspace.employee_rostering.Shift> shiftList) {
		this.shiftList = shiftList;
	}

	public java.util.List<com.myspace.employee_rostering.Skill> getSkillList() {
		return this.skillList;
	}

	public void setSkillList(
			java.util.List<com.myspace.employee_rostering.Skill> skillList) {
		this.skillList = skillList;
	}

	public java.util.List<com.myspace.employee_rostering.Timeslot> getTimeslotList() {
		return this.timeslotList;
	}

	public void setTimeslotList(
			java.util.List<com.myspace.employee_rostering.Timeslot> timeslotList) {
		this.timeslotList = timeslotList;
	}

	public org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore getScore() {
		return this.score;
	}

	public void setScore(
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.score = score;
	}

	public java.util.List<com.myspace.employee_rostering.Employee> getEmployeeList() {
		return this.employeeList;
	}

	public void setEmployeeList(
			java.util.List<com.myspace.employee_rostering.Employee> employeeList) {
		this.employeeList = employeeList;
	}

	public EmployeeRoster(
			java.util.List<com.myspace.employee_rostering.DayOffRequest> dayOffRequestList,
			java.util.List<com.myspace.employee_rostering.ShiftAssignment> shiftAssignmentList,
			java.util.List<com.myspace.employee_rostering.Shift> shiftList,
			java.util.List<com.myspace.employee_rostering.Skill> skillList,
			java.util.List<com.myspace.employee_rostering.Timeslot> timeslotList,
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score,
			java.util.List<com.myspace.employee_rostering.Employee> employeeList) {
		this.dayOffRequestList = dayOffRequestList;
		this.shiftAssignmentList = shiftAssignmentList;
		this.shiftList = shiftList;
		this.skillList = skillList;
		this.timeslotList = timeslotList;
		this.score = score;
		this.employeeList = employeeList;
	}

}