package com.myspace.employee_rostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private Skill skills;

	public Employee() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public com.myspace.employee_rostering.Skill getSkills() {
		return this.skills;
	}

	public void setSkills(com.myspace.employee_rostering.Skill skills) {
		this.skills = skills;
	}

	public Employee(java.lang.String name,
			com.myspace.employee_rostering.Skill skills) {
		this.name = name;
		this.skills = skills;
	}

}