package com.myspace.employee_rostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class ShiftAssignment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"employeeRange"})
	private com.myspace.employee_rostering.Employee employee;
	private com.myspace.employee_rostering.Shift shift;

	public ShiftAssignment() {
	}

	public com.myspace.employee_rostering.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(com.myspace.employee_rostering.Employee employee) {
		this.employee = employee;
	}

	public com.myspace.employee_rostering.Shift getShift() {
		return this.shift;
	}

	public void setShift(com.myspace.employee_rostering.Shift shift) {
		this.shift = shift;
	}

	public ShiftAssignment(com.myspace.employee_rostering.Employee employee,
			com.myspace.employee_rostering.Shift shift) {
		this.employee = employee;
		this.shift = shift;
	}

}